INSERT INTO COUNTRYCODE VALUES ('UA');
INSERT INTO COUNTRYCODE VALUES ('USA');
INSERT INTO COUNTRYCODE VALUES ('UK');

INSERT INTO STATECODE VALUES ('CA');
INSERT INTO STATECODE VALUES ('NY');

INSERT INTO CITY VALUES ('Kyiv', NULL, 'UA');
INSERT INTO CITY VALUES ('London', NULL, 'UK');
INSERT INTO CITY VALUES ('Los Angeles', 'CA', 'USA');

INSERT INTO MARKET VALUES ('Electronics');
INSERT INTO MARKET VALUES ('IoT');
INSERT INTO MARKET VALUES ('Medicine');

INSERT INTO STARTUP VALUES ('Grammarly', 'Kyiv', 'Electronics', 200000, 'https://www.grammarly.com');
INSERT INTO STARTUP VALUES ('Onion', 'London', 'IoT',50000, 'https://onion.io');
INSERT INTO STARTUP VALUES ('Biotechnica', 'Los Angeles', 'Medicine', 500000, NULL);

INSERT INTO INVESTMENT(name, seed, venture) VALUES ('Grammarly', 1000, 0);
INSERT INTO INVESTMENT(name, seed, venture) VALUES ('Onion', 0, 1000);
INSERT INTO INVESTMENT(name, seed, venture) VALUES ('Biotechnica', 2000, 0);

SELECT * FROM STARTUP;

SELECT * FROM INVESTMENT;

